import { CalendarDays,UsersRound,Stethoscope,Building2,Clock3,CheckCircle2 } from 'lucide-react'
import { BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid } from 'recharts'
import { Link } from 'react-router-dom'
import { useApp } from '../context/AppContext'
import { PageTitle,StatCard,Table } from '../components/DashboardBits'
import StatusBadge from '../components/StatusBadge'
export function AdminOverview(){const {appointments,doctors,patients,departments}=useApp();const chart=['Pending','Approved','Completed','Rejected'].map(name=>({name,value:appointments.filter(a=>a.status===name).length}));return <><PageTitle title="Good morning, Admin" text="Here’s what’s happening at Medora today."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard icon={CalendarDays} label="Total appointments" value={appointments.length} trend="12%"/><StatCard icon={Stethoscope} label="Active doctors" value={doctors.length} color="blue"/><StatCard icon={UsersRound} label="Registered patients" value={patients.length} color="emerald"/><StatCard icon={Building2} label="Departments" value={departments.length} color="amber"/></div><div className="mt-6 grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><div className="card"><h2 className="mb-5 text-lg">Appointment overview</h2><div className="h-72"><ResponsiveContainer><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" axisLine={false}/><YAxis allowDecimals={false} axisLine={false}/><Tooltip/><Bar dataKey="value" fill="#08708e" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></div></div><RecentAppointments/></div></>}
export function DoctorOverview(){const {appointments,user,patients}=useApp();const mine=appointments.filter(a=>a.doctorId===user.id);const today=new Date().toISOString().slice(0,10);return <><PageTitle title={`Good morning, ${user.name.split(' ').slice(-1)[0]}`} text="Your schedule and patient activity at a glance."/><div className="grid gap-4 sm:grid-cols-3"><StatCard icon={CalendarDays} label="Today's appointments" value={mine.filter(a=>a.date===today).length}/><StatCard icon={Clock3} label="Pending requests" value={mine.filter(a=>a.status==='Pending').length} color="amber"/><StatCard icon={UsersRound} label="Total patients" value={new Set(mine.map(a=>a.patientId)).size} color="emerald"/></div><div className="mt-6"><AppointmentList appointments={mine.filter(a=>a.date===today)} title="Today's schedule"/></div></>}
export function PatientOverview(){const {appointments,user}=useApp();const mine=appointments.filter(a=>a.patientId===user.id);const next=mine.filter(a=>a.date>=new Date().toISOString().slice(0,10)&&a.status!=='Rejected');return <><PageTitle title={`Hello, ${user.name.split(' ')[0]}!`} text="Stay on top of your appointments and health journey." action={<Link to="/patient/book" className="btn-primary">Book appointment</Link>}/><div className="grid gap-4 sm:grid-cols-3"><StatCard icon={CalendarDays} label="Total appointments" value={mine.length}/><StatCard icon={Clock3} label="Upcoming visits" value={next.length} color="blue"/><StatCard icon={CheckCircle2} label="Completed" value={mine.filter(a=>a.status==='Completed').length} color="emerald"/></div><div className="mt-6"><AppointmentList appointments={next.slice(0,4)} title="Upcoming appointments"/></div></>}
function RecentAppointments(){const {appointments}=useApp();return <AppointmentList appointments={appointments.slice(0,5)} title="Recent appointments"/>}
export function AppointmentList({appointments,title}){const {doctors,patients}=useApp();return <div className="card !p-0 overflow-hidden"><h2 className="p-5 text-lg">{title}</h2><Table heads={['Patient','Doctor','Date & time','Status']} >{appointments.length?appointments.map(a=><tr key={a.id}><td className="px-5 py-4 font-semibold text-navy dark:text-white">{patients.find(p=>p.id===a.patientId)?.name}</td><td className="px-5 py-4">{doctors.find(d=>d.id===a.doctorId)?.name}</td><td className="px-5 py-4">{a.date}<small className="block text-slate-400">{a.time}</small></td><td className="px-5 py-4"><StatusBadge status={a.status}/></td></tr>):<tr><td colSpan="4" className="p-8 text-center text-slate-400">No appointments found</td></tr>}</Table></div>}
