import { useMemo,useState } from 'react'
import { Link } from 'react-router-dom'
import { CalendarPlus,Search,Check,X,Clock3,UserRound,Save } from 'lucide-react'
import { toast } from 'react-toastify'
import { useApp } from '../context/AppContext'
import { PageTitle,Table } from '../components/DashboardBits'
import StatusBadge from '../components/StatusBadge'
import DoctorCard from '../components/DoctorCard'
import EmptyState from '../components/EmptyState'
import BookAppointment from '../pages/BookAppointment'
export function DoctorAppointments({mode='today'}){
 const {appointments,user,patients,updateAppointment}=useApp();const today=new Date().toISOString().slice(0,10);const rows=appointments.filter(a=>a.doctorId===user.id&&(mode==='today'?a.date===today:a.date>today))
 return <><PageTitle title={mode==='today'?"Today's appointments":'Upcoming appointments'} text="Review your schedule and update consultation status."/><div className="card !p-0 overflow-hidden"><Table heads={['Patient','Schedule','Reason','Status','Actions']}>{rows.length?rows.map(a=><tr key={a.id}><td className="px-5 py-4"><b className="text-navy dark:text-white">{patients.find(p=>p.id===a.patientId)?.name}</b><small className="block">{patients.find(p=>p.id===a.patientId)?.phone}</small></td><td className="px-5 py-4">{a.date}<small className="block">{a.time}</small></td><td className="max-w-56 px-5 py-4">{a.reason}</td><td className="px-5 py-4"><StatusBadge status={a.status}/></td><td className="px-5 py-4"><div className="flex gap-1">{a.status==='Pending'&&<><button title="Approve" onClick={()=>updateAppointment(a.id,'Approved')} className="rounded-lg bg-emerald-50 p-2 text-emerald-600"><Check size={17}/></button><button title="Reject" onClick={()=>updateAppointment(a.id,'Rejected')} className="rounded-lg bg-rose-50 p-2 text-rose-600"><X size={17}/></button></>}{a.status==='Approved'&&<button onClick={()=>updateAppointment(a.id,'Completed')} className="rounded-lg bg-brand-50 px-3 py-2 text-xs font-semibold text-brand-700">Complete</button>}</div></td></tr>):<tr><td colSpan="5"><EmptyState title="Your schedule is clear"/></td></tr>}</Table></div></>}
export function DoctorPatients(){const {appointments,user,patients}=useApp();const ids=[...new Set(appointments.filter(a=>a.doctorId===user.id).map(a=>a.patientId))];const rows=patients.filter(p=>ids.includes(p.id));return <><PageTitle title="My patients" text="Patient details from your appointment history."/><div className="card !p-0 overflow-hidden"><Table heads={['Patient','Age / Gender','Blood group','Phone','Location']}>{rows.map(p=><tr key={p.id}><td className="px-5 py-4 font-semibold text-navy dark:text-white">{p.name}</td><td className="px-5 py-4">{p.age} / {p.gender}</td><td className="px-5 py-4">{p.bloodGroup}</td><td className="px-5 py-4">{p.phone}</td><td className="px-5 py-4">{p.address}</td></tr>)}</Table></div></>}
export function Availability(){const {user,updateProfile}=useApp();const [slots,setSlots]=useState(user.available||[]);const [newSlot,setNewSlot]=useState('');const add=()=>{if(newSlot&&!slots.includes(newSlot)){setSlots([...slots,newSlot]);setNewSlot('')}};return <><PageTitle title="Manage availability" text="Set the time slots patients can book."/><div className="card max-w-2xl"><h2 className="text-lg">Consultation slots</h2><div className="mt-5 flex gap-3"><input type="time" className="input" value={newSlot} onChange={e=>setNewSlot(e.target.value)}/><button onClick={add} className="btn-secondary">Add slot</button></div><div className="mt-5 flex flex-wrap gap-2">{slots.map(s=><span className="flex items-center gap-2 rounded-xl bg-brand-50 px-4 py-2 font-semibold text-brand-700" key={s}><Clock3 size={16}/>{s}<button onClick={()=>setSlots(slots.filter(x=>x!==s))}><X size={15}/></button></span>)}</div><button onClick={()=>updateProfile({available:slots})} className="btn-primary mt-7"><Save size={17}/>Save availability</button></div></>}
export function PatientDoctors(){const {doctors,departments}=useApp();const [q,setQ]=useState('');const [dep,setDep]=useState('All');const rows=useMemo(()=>doctors.filter(d=>(dep==='All'||d.department===dep)&&d.name.toLowerCase().includes(q.toLowerCase())),[doctors,q,dep]);return <><PageTitle title="Find a doctor" text="Search trusted specialists and book your next visit."/><div className="mb-6 flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-4 top-3.5 text-slate-400" size={18}/><input className="input !pl-11" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search by doctor name…"/></label><select className="input sm:max-w-64" value={dep} onChange={e=>setDep(e.target.value)}><option>All</option>{departments.map(d=><option key={d.id}>{d.name}</option>)}</select></div><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{rows.map(d=><DoctorCard key={d.id} doctor={d}/>)}</div></>}
export function PatientAppointments(){const {appointments,user,doctors,cancelAppointment}=useApp();const rows=appointments.filter(a=>a.patientId===user.id).sort((a,b)=>b.date.localeCompare(a.date));return <><PageTitle title="My appointments" text="View your upcoming visits and complete appointment history." action={<Link to="/patient/book" className="btn-primary"><CalendarPlus size={17}/>Book new</Link>}/><div className="card !p-0 overflow-hidden"><Table heads={['Doctor','Department','Schedule','Reason','Status','Action']}>{rows.map(a=>{const d=doctors.find(x=>x.id===a.doctorId);return <tr key={a.id}><td className="px-5 py-4 font-semibold text-navy dark:text-white">{d?.name}</td><td className="px-5 py-4">{d?.department}</td><td className="px-5 py-4">{a.date}<small className="block">{a.time}</small></td><td className="max-w-48 truncate px-5 py-4">{a.reason}</td><td className="px-5 py-4"><StatusBadge status={a.status}/></td><td className="px-5 py-4">{['Pending','Approved'].includes(a.status)&&a.date>=new Date().toISOString().slice(0,10)?<button onClick={()=>confirm('Cancel this appointment?')&&cancelAppointment(a.id)} className="text-xs font-semibold text-rose-600">Cancel</button>:'—'}</td></tr>})}</Table></div></>}
export function Profile(){const {user,updateProfile}=useApp();const [form,setForm]=useState(user);const submit=e=>{e.preventDefault();updateProfile(form)};return <><PageTitle title="My profile" text="Keep your personal information up to date."/><form onSubmit={submit} className="card max-w-3xl"><div className="mb-7 flex items-center gap-4 border-b pb-6"><span className="grid size-20 place-items-center rounded-2xl bg-brand-700 text-2xl font-bold text-white">{user.avatar||user.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</span><div><h2 className="text-xl">{user.name}</h2><p className="text-sm capitalize text-slate-500">{user.role} account</p></div></div><div className="grid gap-5 sm:grid-cols-2">{[['Full name','name','text'],['Email','email','email'],['Phone','phone','tel'],['Age','age','number'],['Address','address','text']].map(([l,k,t])=><label key={k}><span className="label">{l}</span><input className="input" type={t} value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div><button className="btn-primary mt-7"><Save size={17}/>Save changes</button></form></>}
export function SettingsPage(){const {theme,setTheme}=useApp();const [notify,setNotify]=useState(true);return <><PageTitle title="Settings" text="Configure your hospital dashboard preferences."/><div className="card max-w-2xl space-y-6"><SettingRow title="Dark mode" text="Use a darker color scheme in the dashboard"><input type="checkbox" checked={theme==='dark'} onChange={()=>setTheme(theme==='dark'?'light':'dark')} className="size-5 accent-brand-700"/></SettingRow><SettingRow title="Appointment notifications" text="Show notifications when appointment status changes"><input type="checkbox" checked={notify} onChange={()=>setNotify(!notify)} className="size-5 accent-brand-700"/></SettingRow><SettingRow title="Local data" text="All application data is stored in this browser"><span className="badge bg-emerald-100 text-emerald-700">Secure locally</span></SettingRow></div></>}
function SettingRow({title,text,children}){return <div className="flex items-center justify-between gap-4 border-b pb-5 last:border-0"><div><h3>{title}</h3><p className="text-sm text-slate-500">{text}</p></div>{children}</div>}
