import { useState } from 'react'
import { Link,useNavigate } from 'react-router-dom'
import { Eye,EyeOff,ShieldCheck,Stethoscope,UserRound } from 'lucide-react'
import { toast } from 'react-toastify'
import Logo from '../components/Logo'
import { useApp } from '../context/AppContext'
export default function Login(){
 const {login}=useApp();const nav=useNavigate();const [show,setShow]=useState(false);const [role,setRole]=useState('patient');const [form,setForm]=useState({email:'',password:''})
 const submit=e=>{e.preventDefault();if(login(form.email,form.password,role))nav(`/${role}`);else toast.error('Invalid email or password')}
 const demo={patient:['patient@demo.com','patient123'],doctor:['ananya@medora.com','doctor123'],admin:['admin@medora.com','admin123']}
 const fill=r=>{setRole(r);setForm({email:demo[r][0],password:demo[r][1]})}
 return <AuthShell><div className="mb-7"><p className="font-bold text-brand-700">WELCOME BACK</p><h1 className="mt-1 text-3xl">Sign in to Medora</h1><p className="mt-2 text-sm text-slate-500">Manage your care in one secure place.</p></div><div className="mb-5 grid grid-cols-3 gap-2">{[['patient',UserRound],['doctor',Stethoscope],['admin',ShieldCheck]].map(([r,I])=><button type="button" onClick={()=>setRole(r)} key={r} className={`rounded-xl border p-3 text-xs font-semibold capitalize transition ${role===r?'border-brand-600 bg-brand-50 text-brand-700 dark:bg-brand-900/20':'bg-white dark:bg-slate-900'}`}><I className="mx-auto mb-1" size={19}/>{r}</button>)}</div><form onSubmit={submit} className="space-y-4"><label><span className="label">Email address</span><input required type="email" className="input" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label><span className="label">Password</span><span className="relative block"><input required type={show?'text':'password'} className="input !pr-11" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button type="button" onClick={()=>setShow(!show)} className="absolute right-3 top-3 text-slate-400">{show?<EyeOff/>:<Eye/>}</button></span></label><button className="btn-primary w-full">Sign in</button></form><p className="mt-5 text-center text-sm">New patient? <Link to="/register" className="font-semibold text-brand-700">Create an account</Link></p><div className="mt-6 rounded-xl bg-slate-50 p-3 text-xs dark:bg-slate-800"><b className="block text-navy dark:text-white">Demo access</b><div className="mt-2 flex gap-2">{Object.keys(demo).map(r=><button key={r} onClick={()=>fill(r)} className="rounded-lg bg-white px-3 py-1.5 capitalize shadow-sm dark:bg-slate-700">{r}</button>)}</div></div></AuthShell>
}
export function Register(){
 const {register}=useApp();const nav=useNavigate();const [form,setForm]=useState({name:'',email:'',phone:'',password:'',gender:'',age:'',bloodGroup:'',address:''})
 const submit=e=>{e.preventDefault();if(form.password.length<6)return toast.error('Password must be at least 6 characters');if(register(form))nav('/patient');else toast.error('An account with this email already exists')}
 return <AuthShell wide><p className="font-bold text-brand-700">PATIENT REGISTRATION</p><h1 className="mb-6 mt-1 text-3xl">Create your account</h1><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2">{[['Full name','name','text'],['Email address','email','email'],['Phone number','phone','tel'],['Password','password','password'],['Age','age','number'],['Address','address','text']].map(([l,k,t])=><label key={k}><span className="label">{l}</span><input required className="input" type={t} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label><span className="label">Gender</span><select required className="input" value={form.gender} onChange={e=>setForm({...form,gender:e.target.value})}><option value="">Select</option><option>Female</option><option>Male</option><option>Other</option></select></label><label><span className="label">Blood group</span><select className="input" value={form.bloodGroup} onChange={e=>setForm({...form,bloodGroup:e.target.value})}><option value="">Select</option>{['A+','A-','B+','B-','AB+','AB-','O+','O-'].map(x=><option key={x}>{x}</option>)}</select></label><button className="btn-primary sm:col-span-2">Create patient account</button></form><p className="mt-5 text-center text-sm">Already registered? <Link to="/login" className="font-semibold text-brand-700">Sign in</Link></p></AuthShell>
}
function AuthShell({children,wide=false}){return <div className="hero-grid min-h-screen bg-gradient-to-br from-brand-50 via-white to-cyan-50 px-4 py-8 dark:from-slate-950 dark:via-slate-900 dark:to-brand-950"><Link to="/" className="mx-auto mb-8 flex w-fit"><Logo/></Link><div className={`mx-auto rounded-3xl border bg-white p-6 shadow-2xl shadow-brand-900/10 dark:bg-slate-900 sm:p-8 ${wide?'max-w-2xl':'max-w-md'}`}>{children}</div></div>}
