import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { ArrowRight,CalendarCheck,ShieldCheck,Clock3,HeartPulse,Brain,Baby,Bone,Stethoscope,Sparkles,CheckCircle2,Play,Star } from 'lucide-react'
import hero from '../assets/hospital-hero.png'
import DoctorCard from '../components/DoctorCard'
import { useApp } from '../context/AppContext'
const icons={HeartPulse,Brain,Baby,Bone,Stethoscope,Sparkles}
export default function Home(){
 const {doctors,departments}=useApp()
 return <div>
  <section className="hero-grid relative overflow-hidden bg-gradient-to-br from-brand-50 via-white to-cyan-50 py-14 dark:from-slate-950 dark:via-slate-900 dark:to-brand-950 lg:py-20"><div className="container-page grid items-center gap-10 lg:grid-cols-[.9fr_1.1fr]">
   <motion.div initial={{opacity:0,x:-30}} animate={{opacity:1,x:0}}><span className="badge mb-5 bg-brand-100 text-brand-800">● Trusted by 50,000+ patients</span><h1 className="text-4xl font-extrabold leading-[1.12] sm:text-5xl lg:text-6xl">Expert care.<br/><span className="text-brand-700">Simply connected.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600 dark:text-slate-300">Find trusted specialists and book your appointment in minutes. Your health deserves care that feels effortless.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/book" className="btn-primary">Book an appointment <ArrowRight size={18}/></Link><Link to="/doctors" className="btn-secondary"><Play size={17}/> Find a doctor</Link></div><div className="mt-8 flex flex-wrap gap-6 text-sm font-medium">{['NABH accredited','24/7 emergency','Secure & private'].map(x=><span key={x} className="flex items-center gap-2"><CheckCircle2 className="text-emerald-500" size={18}/>{x}</span>)}</div></motion.div>
   <motion.div initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} className="relative"><div className="overflow-hidden rounded-[2rem] shadow-2xl shadow-brand-900/15"><img src={hero} alt="Doctor at Medora Hospital" className="h-[420px] w-full object-cover object-center sm:h-[500px]"/></div><div className="absolute -bottom-5 left-4 flex items-center gap-3 rounded-2xl border bg-white p-4 shadow-xl dark:bg-slate-900"><span className="grid size-11 place-items-center rounded-full bg-emerald-100 text-emerald-600"><CalendarCheck/></span><div><b className="block text-navy dark:text-white">Instant booking</b><span className="text-xs text-slate-500">Zero waiting, total convenience</span></div></div><div className="absolute right-4 top-5 rounded-2xl border bg-white/90 p-3 shadow-xl backdrop-blur dark:bg-slate-900/90"><div className="flex text-amber-400">{[1,2,3,4,5].map(x=><Star key={x} size={15} fill="currentColor"/>)}</div><b className="text-sm text-navy dark:text-white">4.9 patient rating</b></div></motion.div>
  </div></section>
  <section className="container-page grid gap-4 py-14 sm:grid-cols-3">{[[CalendarCheck,'Book in minutes','Choose a doctor and your preferred slot.'],[ShieldCheck,'Trusted specialists','Verified doctors with years of expertise.'],[Clock3,'Care when you need it','Same-day appointments and 24/7 support.']].map(([I,t,d])=><div key={t} className="flex gap-4 rounded-2xl border bg-white p-5 dark:bg-slate-900"><span className="grid size-12 shrink-0 place-items-center rounded-xl bg-brand-50 text-brand-700 dark:bg-brand-900/30"><I/></span><div><h3>{t}</h3><p className="mt-1 text-sm text-slate-500">{d}</p></div></div>)}</section>
  <section className="bg-white py-20 dark:bg-slate-900/50"><div className="container-page"><div className="mb-10 flex items-end justify-between"><div><p className="font-bold uppercase tracking-widest text-brand-600">Our specialties</p><h2 className="mt-2 text-3xl sm:text-4xl">Care across every specialty</h2></div><Link to="/departments" className="hidden font-semibold text-brand-700 sm:flex">View all <ArrowRight/></Link></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{departments.slice(0,6).map(d=>{const I=icons[d.icon]||Stethoscope;return <Link to={`/doctors?department=${d.name}`} key={d.id} className="group rounded-2xl border bg-slate-50 p-6 transition hover:-translate-y-1 hover:border-brand-300 hover:bg-brand-50 dark:bg-slate-900"><span className="grid size-12 place-items-center rounded-xl bg-white text-brand-700 shadow-sm dark:bg-slate-800"><I/></span><h3 className="mt-5 text-xl">{d.name}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{d.description}</p><span className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-brand-700">Explore care <ArrowRight size={16} className="transition group-hover:translate-x-1"/></span></Link>})}</div></div></section>
  <section className="container-page py-20"><div className="mb-10 text-center"><p className="font-bold uppercase tracking-widest text-brand-600">Meet our experts</p><h2 className="mt-2 text-3xl sm:text-4xl">Doctors patients trust</h2><p className="mx-auto mt-3 max-w-xl text-slate-500">Experienced specialists, dedicated to helping you feel your best.</p></div><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{doctors.slice(0,3).map(d=><DoctorCard key={d.id} doctor={d}/>)}</div><div className="mt-9 text-center"><Link className="btn-secondary" to="/doctors">View all doctors <ArrowRight size={17}/></Link></div></section>
  <section className="container-page"><div className="overflow-hidden rounded-[2rem] bg-gradient-to-r from-brand-800 to-brand-600 px-6 py-12 text-center text-white sm:px-12"><HeartPulse className="mx-auto mb-4" size={36}/><h2 className="text-3xl text-white">Your health can’t wait.</h2><p className="mx-auto mt-3 max-w-xl text-brand-100">Schedule a consultation with one of our specialists today.</p><Link to="/book" className="mt-7 inline-flex rounded-xl bg-white px-6 py-3 font-bold text-brand-800">Book your visit <ArrowRight className="ml-2"/></Link></div></section>
 </div>
}
