import { useState } from 'react'
import { NavLink,Outlet,useNavigate } from 'react-router-dom'
import { LayoutDashboard,UsersRound,CalendarDays,Building2,BarChart3,Settings,UserRound,Stethoscope,Clock3,History,LogOut,Menu,X,PanelLeftClose,Search } from 'lucide-react'
import Logo from '../components/Logo'
import ThemeButton from '../components/ThemeButton'
import { useApp } from '../context/AppContext'
const menus={
 admin:[[LayoutDashboard,'Overview','/admin'],[Stethoscope,'Doctors','/admin/doctors'],[UsersRound,'Patients','/admin/patients'],[CalendarDays,'Appointments','/admin/appointments'],[Building2,'Departments','/admin/departments'],[BarChart3,'Reports','/admin/reports'],[Settings,'Settings','/admin/settings'],[UserRound,'Profile','/admin/profile']],
 doctor:[[LayoutDashboard,'Overview','/doctor'],[CalendarDays,"Today's visits",'/doctor/today'],[Clock3,'Upcoming','/doctor/upcoming'],[UsersRound,'Patients','/doctor/patients'],[Settings,'Availability','/doctor/availability'],[UserRound,'Profile','/doctor/profile']],
 patient:[[LayoutDashboard,'Overview','/patient'],[Stethoscope,'Find doctors','/patient/doctors'],[CalendarDays,'Book appointment','/patient/book'],[History,'My appointments','/patient/appointments'],[UserRound,'My profile','/patient/profile']]
}
export default function DashboardLayout(){
 const [open,setOpen]=useState(false);const {user,logout}=useApp();const nav=useNavigate();const items=menus[user?.role]||[]
 return <div className="min-h-screen bg-slate-50 dark:bg-slate-950"><aside className={`fixed inset-y-0 left-0 z-50 flex w-72 flex-col border-r bg-white p-4 transition-transform dark:bg-slate-900 lg:translate-x-0 ${open?'translate-x-0':'-translate-x-full'}`}><div className="flex items-center justify-between p-2"><Logo/><button onClick={()=>setOpen(false)} className="lg:hidden"><X/></button></div><div className="mt-7 flex items-center gap-3 rounded-2xl bg-brand-50 p-3 dark:bg-brand-900/20"><span className="grid size-11 place-items-center rounded-xl bg-brand-700 font-bold text-white">{user?.avatar||user?.name?.split(' ').map(x=>x[0]).join('').slice(0,2)}</span><div className="min-w-0"><b className="block truncate text-sm text-navy dark:text-white">{user?.name}</b><span className="text-xs capitalize text-slate-500">{user?.role} account</span></div></div><nav className="scrollbar mt-6 flex-1 space-y-1 overflow-y-auto">{items.map(([I,n,p])=><NavLink end={p===`/${user?.role}`} onClick={()=>setOpen(false)} to={p} key={p} className={({isActive})=>`flex items-center gap-3 rounded-xl px-4 py-3 text-sm font-semibold transition ${isActive?'bg-brand-700 text-white shadow-lg shadow-brand-700/20':'text-slate-500 hover:bg-brand-50 hover:text-brand-700 dark:hover:bg-slate-800'}`}><I size={19}/>{n}</NavLink>)}</nav><button onClick={()=>{logout();nav('/')}} className="flex items-center gap-3 rounded-xl px-4 py-3 text-sm font-semibold text-rose-500 hover:bg-rose-50"><LogOut size={19}/>Sign out</button></aside><div className="lg:pl-72"><header className="sticky top-0 z-30 flex h-18 items-center justify-between border-b bg-white/90 px-4 backdrop-blur dark:bg-slate-900/90 sm:px-7"><button onClick={()=>setOpen(true)} className="lg:hidden"><Menu/></button><div className="hidden max-w-sm flex-1 items-center gap-2 rounded-xl bg-slate-100 px-4 py-2.5 text-slate-400 dark:bg-slate-800 sm:flex"><Search size={17}/><span className="text-sm">Search anything…</span></div><div className="ml-auto flex items-center gap-3"><ThemeButton/><div className="hidden text-right sm:block"><b className="block text-sm text-navy dark:text-white">{user?.name}</b><span className="text-xs capitalize text-slate-500">{user?.role}</span></div><span className="grid size-10 place-items-center rounded-full bg-gradient-to-br from-brand-600 to-cyan-400 font-bold text-white">{user?.avatar||user?.name?.[0]}</span></div></header><main className="p-4 sm:p-7"><Outlet/></main></div></div>
}
